version: '3.8'
services:

  traefik:
    networks:
      development:
        aliases:
          - ${GITPOD_WORKSPACE_URL}
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  php:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financialfreedom.rule=HostRegexp(`443-debug-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}`)"
      - "traefik.http.routers.financialfreedom.entrypoints=websecure"
      - "traefik.http.routers.financialfreedom.tls=true"
      - "traefik.http.services.financialfreedom.loadbalancer.server.port=80"
      - "traefik.http.services.financialfreedom.loadbalancer.server.scheme=http"

  node:
    command: yarn install

  mailpit:
    ports:
      - 8025:8025
    labels:
      - "traefik.enable=false"

networks:
  development: