version: '3.8'
services:

  traefik:
    restart: "no"
    networks:
      development:
        aliases:
          - financialfreedom.dev.test
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.infrastructure/conf/traefik/dev/traefik.yml:/traefik.yml:ro
      - ./.infrastructure/conf/traefik/dev/traefik-certs.yml:/traefik-certs.yml
      - ./.infrastructure/conf/traefik/dev/certificates/:/certificates
  
  mariadb:
    networks:
      - development
    volumes:
      - ./.infrastructure/volume_data/mariadb/database_data/:/var/lib/mysql
    environment:
        MARIADB_ROOT_PASSWORD: "rootpassword"
        MARIADB_DATABASE: "financialfreedom"
        MARIADB_USER: "financialfreedom_dbuser"
        MARIADB_PASSWORD: "financialfreedom_dbpassword"
    ports:
      - 3306:3306

  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    volumes:
      - .:/var/www/html/
    networks:
      - development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financialfreedom.rule=Host(`financialfreedom.dev.test`)"
      - "traefik.http.routers.financialfreedom.entrypoints=websecure"
      - "traefik.http.routers.financialfreedom.tls=true"
      - "traefik.http.services.financialfreedom.loadbalancer.server.port=443"
      - "traefik.http.services.financialfreedom.loadbalancer.server.scheme=https"
    environment:
      # LOG_LEVEL: "debug" # 🔥 Uncomment for debugging
      AUTORUN_ENABLED: "false"
      SSL_MODE: "full"

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        USER_ID: ${SPIN_USER_ID}
    networks:
      - development
    volumes:
      - .:/usr/src/app/:cached
    working_dir: /usr/src/app/

  mailpit:
    image: axllent/mailpit
    networks:
      - development
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.dev.test`)"
      - "traefik.http.routers.mailpit.entrypoints=websecure"
      - "traefik.http.routers.mailpit.tls=true"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
      - "traefik.http.services.mailpit.loadbalancer.server.scheme=http"

networks:
  development: