name: Docker Publish (Edge Image)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
        - 'docs/**'
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build-edge:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      docker-tags: "serversideup/financial-freedom:edge"
      dockerfile: "./Dockerfile.php"
    secrets: inherit