name: Docker Publish (Beta Image)

on:
  workflow_dispatch:
  push:
    branches:
      - 56-create-a-docker-hub-image-for-easy-deployments
    paths-ignore:
        - 'docs/**'
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      docker-tags: "serversideup/financial-freedom:beta"
      dockerfile: "./Dockerfile.php"
    secrets: inherit