on:
  workflow_call:
    inputs:
      platforms:
        type: string
        default: 'linux/amd64,linux/arm/v7,linux/arm64/v8'
      docker-tags:
        required: true
        type: string
      dockerfile:
        type: string
        default: './Dockerfile'

jobs:
  docker-publish:
    runs-on: ubuntu-22.04
    steps:

      - name: docker-build-action
        uses: serversideup/github-action-docker-build@main
        with:
          tags: "${{ inputs.docker-tags }}"
          dockerfile: "${{ inputs.dockerfile }}"
          registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          registry-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          platforms: "${{ inputs.platforms }}"