on:
  workflow_call:

env:
  DOCKER_COMPOSE_CMD: docker compose -f docker-compose.yml -f docker-compose.ci.yml

jobs:
  php-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Restore composer cache (if available)
        id: node-modules-restore
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
         
      - if: ${{ steps.node-modules-restore.outputs.cache-hit != 'true' }}
        name: Run "yarn install"
        run: |
          $DOCKER_COMPOSE_CMD \
          run \
          node \
          yarn install --frozen-lockfile

      - name: Run "yarn production"
        run: |
          $DOCKER_COMPOSE_CMD \
          run \
          node \
          yarn production

      - name: Upload node_modules cache
        uses: actions/cache/save@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}